// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm790hvG9oBT2-JqjF29tS0nP0o15NS08',
    appId: '1:102359149018:web:90734e1929c8819af678e3',
    messagingSenderId: '102359149018',
    projectId: 'fuzzysnap-da9b4',
    authDomain: 'fuzzysnap-da9b4.firebaseapp.com',
    storageBucket: 'fuzzysnap-da9b4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxgn4QMBcUram7Z-8Xx1Xrt1YUfS6N5kI',
    appId: '1:102359149018:android:6d53da3637573e73f678e3',
    messagingSenderId: '102359149018',
    projectId: 'fuzzysnap-da9b4',
    storageBucket: 'fuzzysnap-da9b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu_yrKr1wRhfWRO0dW9YDjLtjtjeQLw5Y',
    appId: '1:102359149018:ios:53f250b446d0f7daf678e3',
    messagingSenderId: '102359149018',
    projectId: 'fuzzysnap-da9b4',
    storageBucket: 'fuzzysnap-da9b4.appspot.com',
    iosBundleId: 'com.example.fuzzysnap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDu_yrKr1wRhfWRO0dW9YDjLtjtjeQLw5Y',
    appId: '1:102359149018:ios:53f250b446d0f7daf678e3',
    messagingSenderId: '102359149018',
    projectId: 'fuzzysnap-da9b4',
    storageBucket: 'fuzzysnap-da9b4.appspot.com',
    iosBundleId: 'com.example.fuzzysnap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDm790hvG9oBT2-JqjF29tS0nP0o15NS08',
    appId: '1:102359149018:web:5fa30666f3b1e219f678e3',
    messagingSenderId: '102359149018',
    projectId: 'fuzzysnap-da9b4',
    authDomain: 'fuzzysnap-da9b4.firebaseapp.com',
    storageBucket: 'fuzzysnap-da9b4.appspot.com',
  );
}
